language: php
 
php:
  - 7.0
  - 7.1
  - master  
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: master

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
 
script: phpunit
